; Generated by Simple Compiler

section .text
global _start

print_int:
    push rbp
    mov  rbp, rsp
    sub  rsp, 64
    mov  rax, rdi
    mov  r8,  0
    mov  rbx, 10
.pi_convert:
    xor  rdx, rdx
    div  rbx
    add  dl, '0'
    dec  rsp
    mov  [rsp], dl
    inc  r8
    test rax, rax
    jnz  .pi_convert
.pi_print:
    test r8, r8
    jz   .pi_newline
    mov  rax, 1
    mov  rdi, 1
    mov  rsi, rsp
    mov  rdx, 1
    syscall
    inc  rsp
    dec  r8
    jmp  .pi_print
.pi_newline:
    mov  byte [rbp-1], 10
    mov  rax, 1
    mov  rdi, 1
    lea  rsi, [rbp-1]
    mov  rdx, 1
    syscall
    mov  rsp, rbp
    pop  rbp
    ret

print_str:
    push rbp
    mov  rbp, rsp
    sub  rsp, 16
    mov  r8, 0
.ps_len:
    mov  al, [rdi + r8]
    test al, al
    jz   .ps_write
    inc  r8
    jmp  .ps_len
.ps_write:
    test r8, r8
    jz   .ps_newline
    mov  rax, 1
    mov  rsi, rdi
    mov  rdx, r8
    mov  rdi, 1
    syscall
.ps_newline:
    mov  byte [rbp-1], 10
    mov  rax, 1
    mov  rdi, 1
    lea  rsi, [rbp-1]
    mov  rdx, 1
    syscall
    mov  rsp, rbp
    pop  rbp
    ret

add:
    push rbp
    mov  rbp, rsp
    sub  rsp, 8
    mov  [rbp - 8], rdi
    sub  rsp, 8
    mov  [rbp - 16], rsi
    mov  rax, [rbp - 8]
    push rax
    mov  rax, [rbp - 16]
    mov  rbx, rax
    pop  rax
    add  rax, rbx
    jmp  .L_ret_add
.L_ret_add:
    mov  rsp, rbp
    pop  rbp
    ret

_start:
    push rbp
    mov  rbp, rsp
    ; call add
    mov  rax, 3
    push rax
    mov  rax, 4
    push rax
    pop  rsi
    pop  rdi
    call add
    mov  rdi, rax
    call print_int
.L_ret_main:
    mov  rsp, rbp
    pop  rbp
    mov  rax, 60
    mov  rdi, 0
    syscall

