; Generated by Simple C Compiler

section .text
global _start

_start:
    push rbp
    mov rbp, rsp
    sub rsp, 8
    mov rax, 62
    mov [rbp - 8], rax
    sub rsp, 8
    mov rax, 0
    mov [rbp - 16], rax
    mov rax, [rbp - 8]
    push rax
    mov rax, 1000
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setg al
    movzx rax, al
    cmp rax, 0
    je .L0
    mov rax, 1
    mov [rbp - 16], rax
    jmp .L1
.L0:
    mov rax, 0
    mov [rbp - 16], rax
.L1:
    mov rax, [rbp - 16]
    mov rdi, rax
    jmp .L_return
.L_return:
    mov rsp, rbp
    pop rbp
    mov rax, 60
    syscall
