; Generated by Simple Compiler

section .text
global _start

print_int:
    push rbp
    mov  rbp, rsp
    sub  rsp, 64
    mov  rax, rdi
    mov  r8,  0
    mov  rbx, 10
.pi_convert:
    xor  rdx, rdx
    div  rbx
    add  dl, '0'
    dec  rsp
    mov  [rsp], dl
    inc  r8
    test rax, rax
    jnz  .pi_convert
.pi_print:
    test r8, r8
    jz   .pi_newline
    mov  rax, 1
    mov  rdi, 1
    mov  rsi, rsp
    mov  rdx, 1
    syscall
    inc  rsp
    dec  r8
    jmp  .pi_print
.pi_newline:
    mov  byte [rbp-1], 10
    mov  rax, 1
    mov  rdi, 1
    lea  rsi, [rbp-1]
    mov  rdx, 1
    syscall
    mov  rsp, rbp
    pop  rbp
    ret

print_str:
    push rbp
    mov  rbp, rsp
    sub  rsp, 16
    mov  r8, 0
.ps_len:
    mov  al, [rdi + r8]
    test al, al
    jz   .ps_write
    inc  r8
    jmp  .ps_len
.ps_write:
    test r8, r8
    jz   .ps_newline
    mov  rax, 1
    mov  rsi, rdi
    mov  rdx, r8
    mov  rdi, 1
    syscall
.ps_newline:
    mov  byte [rbp-1], 10
    mov  rax, 1
    mov  rdi, 1
    lea  rsi, [rbp-1]
    mov  rdx, 1
    syscall
    mov  rsp, rbp
    pop  rbp
    ret

list_alloc:
    push rbp
    mov  rbp, rsp
    push rbx
    push r12
    push r13
    mov  r12, rdi
    mov  r13, rdi
    imul r13, 2
    cmp  r13, 8
    jge  .la_cap_ok
    mov  r13, 8
.la_cap_ok:
    xor  rdi, rdi
    mov  rax, 12
    syscall
    mov  rbx, rax
    mov  rdi, rax
    mov  rcx, r13
    imul rcx, 8
    add  rdi, rcx
    add  rdi, 16
    mov  rax, 12
    syscall
    mov  [rbx],     r12
    mov  [rbx + 8], r13
    mov  rax, rbx
    pop  r13
    pop  r12
    pop  rbx
    mov  rsp, rbp
    pop  rbp
    ret

list_push:
    push rbp
    mov  rbp, rsp
    push rbx
    push r12
    push r13
    push r14
    mov  rbx, rdi
    mov  r12, rsi
    mov  r13, [rbx]
    mov  r14, [rbx + 8]
    cmp  r13, r14
    jl   .lp_has_space
    imul r14, 2
    mov  [rbx + 8], r14
    xor  rdi, rdi
    mov  rax, 12
    syscall
    mov  rdi, rax
    mov  rcx, r14
    imul rcx, 8
    add  rdi, rcx
    add  rdi, 16
    mov  rax, 12
    syscall
.lp_has_space:
    mov  rcx, r13
    imul rcx, 8
    add  rcx, 16
    mov  [rbx + rcx], r12
    inc  r13
    mov  [rbx], r13
    pop  r14
    pop  r13
    pop  r12
    pop  rbx
    mov  rsp, rbp
    pop  rbp
    ret

list_len:
    mov  rax, [rdi]
    ret

_start:
    push rbp
    mov  rbp, rsp
    lea  rdi, [rel str0]
    call print_str
    sub  rsp, 8
    mov  rax, 1
    mov  [rbp - 8], rax
.L0:
    mov  rax, [rbp - 8]
    push rax
    mov  rax, 6
    mov  rbx, rax
    pop  rax
    cmp rax,rbx
    setl  al
    movzx rax,al
    cmp  rax, 0
    je   .L2
    mov  rax, [rbp - 8]
    push rax
    mov  rax, 3
    mov  rbx, rax
    pop  rax
    cmp rax,rbx
    sete  al
    movzx rax,al
    cmp  rax, 0
    je   .L3
    jmp  .L1
    jmp  .L4
.L3:
.L4:
    mov  rdi, [rbp - 8]
    call print_int
.L1:
    mov  rax, [rbp - 8]
    push rax
    mov  rax, 1
    mov  rbx, rax
    pop  rax
    add  rax, rbx
    mov  [rbp - 8], rax
    jmp  .L0
.L2:
.L_ret_main:
    mov  rsp, rbp
    pop  rbp
    mov  rax, 60
    mov  rdi, 0
    syscall


section .data
str0 db "Test 7: skip still increments for counter", 0
