#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ─────────────────────────────────────────
   Variable / parameter offset map
   is_string = 1  →  slot holds a pointer (print_str)
   is_string = 0  →  slot holds an integer (print_int)
───────────────────────────────────────── */

typedef struct VarOffset {
    char* name;
    int   offset;    /* positive = [rbp - offset] */
    int   is_string;
    struct VarOffset* next;
} VarOffset;

static VarOffset* var_list     = NULL;
static int current_offset      = 0;
static char data_section[10000] = "";
static int str_count           = 0;

/* ─────────────────────────────────────────
   Variable helpers
───────────────────────────────────────── */

static VarOffset* find_var(const char* name) {
    for (VarOffset* v = var_list; v; v = v->next)
        if (strcmp(v->name, name) == 0) return v;
    return NULL;
}

static int get_variable_offset(const char* name) {
    VarOffset* v = find_var(name);
    return v ? v->offset : -1;
}

static int get_variable_is_string(const char* name) {
    VarOffset* v = find_var(name);
    return v ? v->is_string : 0;
}

static void add_variable(const char* name, int offset, int is_string) {
    VarOffset* v = malloc(sizeof(VarOffset));
    v->name      = strdup(name);
    v->offset    = offset;
    v->is_string = is_string;
    v->next      = var_list;
    var_list     = v;
}

/* Free the entire var list (called between functions) */
static void free_var_list(void) {
    VarOffset* curr = var_list;
    while (curr) {
        VarOffset* next = curr->next;
        free(curr->name);
        free(curr);
        curr = next;
    }
    var_list      = NULL;
    current_offset = 0;
}

static int new_label(CodeGenerator* g) { return g->label_counter++; }

/* ─────────────────────────────────────────
   String literal pool
───────────────────────────────────────── */

static int register_string(const char* value) {
    int id = str_count++;
    char buf[1024];
    snprintf(buf, sizeof(buf), "str%d db \"%s\", 0\n", id, value);
    strncat(data_section, buf, sizeof(data_section) - strlen(data_section) - 1);
    return id;
}

/* ─────────────────────────────────────────
   Linux x86-64 integer argument registers
   (System V AMD64 ABI: rdi, rsi, rdx, rcx, r8, r9)
───────────────────────────────────────── */

static const char* ARG_REGS[] = { "rdi", "rsi", "rdx", "rcx", "r8", "r9" };
#define MAX_REG_ARGS 6

/* ─────────────────────────────────────────
   PROLOGUE  (print_int + print_str helpers)
───────────────────────────────────────── */

static void generate_prologue(CodeGenerator* g) {

    fprintf(g->output, "; Generated by Simple Compiler\n\n");
    fprintf(g->output, "section .text\n");
    fprintf(g->output, "global _start\n\n");

    /* ── print_int(rdi = non-negative integer) ── */
    fprintf(g->output,
        "print_int:\n"
        "    push rbp\n"
        "    mov  rbp, rsp\n"
        "    sub  rsp, 64\n"
        "    mov  rax, rdi\n"
        "    mov  r8,  0\n"
        "    mov  rbx, 10\n"
        ".pi_convert:\n"
        "    xor  rdx, rdx\n"
        "    div  rbx\n"
        "    add  dl, '0'\n"
        "    dec  rsp\n"
        "    mov  [rsp], dl\n"
        "    inc  r8\n"
        "    test rax, rax\n"
        "    jnz  .pi_convert\n"
        ".pi_print:\n"
        "    test r8, r8\n"
        "    jz   .pi_newline\n"
        "    mov  rax, 1\n"
        "    mov  rdi, 1\n"
        "    mov  rsi, rsp\n"
        "    mov  rdx, 1\n"
        "    syscall\n"
        "    inc  rsp\n"
        "    dec  r8\n"
        "    jmp  .pi_print\n"
        ".pi_newline:\n"
        "    mov  byte [rbp-1], 10\n"
        "    mov  rax, 1\n"
        "    mov  rdi, 1\n"
        "    lea  rsi, [rbp-1]\n"
        "    mov  rdx, 1\n"
        "    syscall\n"
        "    mov  rsp, rbp\n"
        "    pop  rbp\n"
        "    ret\n\n"
    );

    /* ── print_str(rdi = null-terminated string pointer) ── */
    fprintf(g->output,
        "print_str:\n"
        "    push rbp\n"
        "    mov  rbp, rsp\n"
        "    sub  rsp, 16\n"
        "    mov  r8, 0\n"
        ".ps_len:\n"
        "    mov  al, [rdi + r8]\n"
        "    test al, al\n"
        "    jz   .ps_write\n"
        "    inc  r8\n"
        "    jmp  .ps_len\n"
        ".ps_write:\n"
        "    test r8, r8\n"
        "    jz   .ps_newline\n"
        "    mov  rax, 1\n"
        "    mov  rsi, rdi\n"
        "    mov  rdx, r8\n"
        "    mov  rdi, 1\n"
        "    syscall\n"
        ".ps_newline:\n"
        "    mov  byte [rbp-1], 10\n"
        "    mov  rax, 1\n"
        "    mov  rdi, 1\n"
        "    lea  rsi, [rbp-1]\n"
        "    mov  rdx, 1\n"
        "    syscall\n"
        "    mov  rsp, rbp\n"
        "    pop  rbp\n"
        "    ret\n\n"
    );
}

/* ─────────────────────────────────────────
   Forward declaration
───────────────────────────────────────── */

static void generate_expression(CodeGenerator* g, ASTNode* expr);

/* ─────────────────────────────────────────
   output() dispatcher  →  print_str or print_int
───────────────────────────────────────── */

static void emit_output(CodeGenerator* g, ASTNode* arg) {
    if (!arg) return;

    if (arg->type == AST_STRING) {
        int id = register_string(arg->data.string_value);
        fprintf(g->output, "    lea  rdi, [rel str%d]\n", id);
        fprintf(g->output, "    call print_str\n");

    } else if (arg->type == AST_IDENTIFIER &&
               get_variable_is_string(arg->data.identifier)) {
        int offset = get_variable_offset(arg->data.identifier);
        fprintf(g->output, "    mov  rdi, [rbp - %d]\n", offset);
        fprintf(g->output, "    call print_str\n");

    } else {
        generate_expression(g, arg);
        fprintf(g->output, "    mov  rdi, rax\n");
        fprintf(g->output, "    call print_int\n");
    }
}

/* ─────────────────────────────────────────
   EXPRESSION GENERATOR
───────────────────────────────────────── */

static void generate_expression(CodeGenerator* g, ASTNode* expr) {
    if (!expr) return;

    switch (expr->type) {

        case AST_INTEGER:
            fprintf(g->output, "    mov  rax, %d\n", expr->data.int_value);
            break;

        case AST_CHAR:
            fprintf(g->output, "    mov  rax, %d\n", (int)expr->data.char_value);
            break;

        case AST_STRING: {
            int id = register_string(expr->data.string_value);
            fprintf(g->output, "    lea  rax, [rel str%d]\n", id);
            break;
        }

        case AST_IDENTIFIER: {
            int offset = get_variable_offset(expr->data.identifier);
            if (offset < 0) {
                fprintf(stderr, "CodeGen Error: Undefined variable '%s'\n",
                        expr->data.identifier);
                exit(1);
            }
            fprintf(g->output, "    mov  rax, [rbp - %d]\n", offset);
            break;
        }

        case AST_BINARY_OP: {
            generate_expression(g, expr->data.binary.left);
            fprintf(g->output, "    push rax\n");
            generate_expression(g, expr->data.binary.right);
            fprintf(g->output, "    mov  rbx, rax\n");
            fprintf(g->output, "    pop  rax\n");

            switch (expr->data.binary.op) {
                case TOKEN_PLUS:  fprintf(g->output, "    add  rax, rbx\n"); break;
                case TOKEN_MINUS: fprintf(g->output, "    sub  rax, rbx\n"); break;
                case TOKEN_STAR:  fprintf(g->output, "    imul rax, rbx\n"); break;
                case TOKEN_SLASH:
                    fprintf(g->output, "    cqo\n");
                    fprintf(g->output, "    idiv rbx\n"); break;
                case TOKEN_GREATER:
                    fprintf(g->output, "    cmp  rax, rbx\n");
                    fprintf(g->output, "    setg al\n");
                    fprintf(g->output, "    movzx rax, al\n"); break;
                case TOKEN_LESS:
                    fprintf(g->output, "    cmp  rax, rbx\n");
                    fprintf(g->output, "    setl al\n");
                    fprintf(g->output, "    movzx rax, al\n"); break;
                case TOKEN_GREATER_EQUAL:
                    fprintf(g->output, "    cmp  rax, rbx\n");
                    fprintf(g->output, "    setge al\n");
                    fprintf(g->output, "    movzx rax, al\n"); break;
                case TOKEN_LESS_EQUAL:
                    fprintf(g->output, "    cmp  rax, rbx\n");
                    fprintf(g->output, "    setle al\n");
                    fprintf(g->output, "    movzx rax, al\n"); break;
                case TOKEN_EQUAL:
                    fprintf(g->output, "    cmp  rax, rbx\n");
                    fprintf(g->output, "    sete al\n");
                    fprintf(g->output, "    movzx rax, al\n"); break;
                case TOKEN_NOT_EQUAL:
                    fprintf(g->output, "    cmp  rax, rbx\n");
                    fprintf(g->output, "    setne al\n");
                    fprintf(g->output, "    movzx rax, al\n"); break;
                default:
                    fprintf(stderr, "CodeGen Error: Unsupported operator\n");
                    exit(1);
            }
            break;
        }

        /*
         * Function call used as expression.
         *
         * Calling convention (System V AMD64):
         *   - First 6 integer args go in rdi, rsi, rdx, rcx, r8, r9.
         *   - Further args pushed right-to-left onto stack.
         *   - Return value in rax.
         *   - Caller saves rdi/rsi/rdx/rcx/r8/r9/r10/r11/rax if needed.
         *
         * We evaluate each argument into rax, then move it into the
         * correct register (or push it for args > 6).
         * We push all arg registers first to protect them from being
         * clobbered by evaluating subsequent arguments.
         */
        case AST_FUNCTION_CALL: {
            const char* fname = expr->data.func_call.name;
            int nargs         = expr->data.func_call.arg_count;

            /* built-in output() */
            if (strcmp(fname, "output") == 0 && nargs > 0) {
                emit_output(g, expr->data.func_call.arguments[0]);
                break;
            }

            /* user-defined function call */
            fprintf(g->output, "    ; call %s\n", fname);

            /*
             * Evaluate each argument onto a temporary stack area,
             * then load them into the ABI registers.
             * This avoids clobbering rdi/rsi/... while evaluating
             * later arguments that might read variables from [rbp-…].
             */
            for (int i = 0; i < nargs && i < MAX_REG_ARGS; i++) {
                generate_expression(g, expr->data.func_call.arguments[i]);
                fprintf(g->output, "    push rax\n");
            }
            /* handle extra args (>6): already on stack in reverse order — noop here */

            /* pop from stack into argument registers in reverse order */
            for (int i = (nargs < MAX_REG_ARGS ? nargs : MAX_REG_ARGS) - 1; i >= 0; i--) {
                fprintf(g->output, "    pop  %s\n", ARG_REGS[i]);
            }

            fprintf(g->output, "    call %s\n", fname);
            /* return value is in rax — caller uses it */
            break;
        }

        default:
            break;
    }
}

/* ─────────────────────────────────────────
   STATEMENT GENERATOR
───────────────────────────────────────── */

static void generate_statement(CodeGenerator* g, ASTNode* stmt) {
    if (!stmt) return;

    switch (stmt->type) {

        case AST_VAR_DECL: {
            current_offset += 8;
            int is_str = (stmt->data.var_decl.initializer &&
                          stmt->data.var_decl.initializer->type == AST_STRING) ? 1 : 0;
            add_variable(stmt->data.var_decl.name, current_offset, is_str);
            fprintf(g->output, "    sub  rsp, 8\n");
            if (stmt->data.var_decl.initializer) {
                if (is_str) {
                    int id = register_string(
                        stmt->data.var_decl.initializer->data.string_value);
                    fprintf(g->output, "    lea  rax, [rel str%d]\n", id);
                } else {
                    generate_expression(g, stmt->data.var_decl.initializer);
                }
                fprintf(g->output, "    mov  [rbp - %d], rax\n", current_offset);
            }
            break;
        }

        case AST_FUNCTION_CALL: {
            if (strcmp(stmt->data.func_call.name, "output") == 0 &&
                stmt->data.func_call.arg_count > 0) {
                emit_output(g, stmt->data.func_call.arguments[0]);
            } else {
                /* call user function as statement (discard return value) */
                ASTNode tmp;
                tmp.type = AST_FUNCTION_CALL;
                tmp.data.func_call = stmt->data.func_call;
                generate_expression(g, &tmp);
            }
            break;
        }

        case AST_ASSIGNMENT: {
            int offset = get_variable_offset(stmt->data.assignment.name);
            if (offset < 0) {
                fprintf(stderr, "CodeGen Error: Undefined variable '%s'\n",
                        stmt->data.assignment.name);
                exit(1);
            }
            generate_expression(g, stmt->data.assignment.value);
            fprintf(g->output, "    mov  [rbp - %d], rax\n", offset);
            break;
        }

        case AST_RETURN: {
            if (stmt->data.return_value)
                generate_expression(g, stmt->data.return_value);
            /* return value already in rax — jump to function epilogue */
            fprintf(g->output, "    jmp  .L_ret_%s\n", g->current_function);
            break;
        }

        case AST_IF: {
            int else_lbl = new_label(g);
            int end_lbl  = new_label(g);
            generate_expression(g, stmt->data.if_stmt.condition);
            fprintf(g->output, "    cmp  rax, 0\n");
            fprintf(g->output, "    je   .L%d\n", else_lbl);
            generate_statement(g, stmt->data.if_stmt.then_branch);
            fprintf(g->output, "    jmp  .L%d\n", end_lbl);
            fprintf(g->output, ".L%d:\n", else_lbl);
            if (stmt->data.if_stmt.else_branch)
                generate_statement(g, stmt->data.if_stmt.else_branch);
            fprintf(g->output, ".L%d:\n", end_lbl);
            break;
        }

        case AST_WHILE: {
            int start_lbl = new_label(g);
            int end_lbl   = new_label(g);
            fprintf(g->output, ".L%d:\n", start_lbl);
            generate_expression(g, stmt->data.while_stmt.condition);
            fprintf(g->output, "    cmp  rax, 0\n");
            fprintf(g->output, "    je   .L%d\n", end_lbl);
            generate_statement(g, stmt->data.while_stmt.body);
            fprintf(g->output, "    jmp  .L%d\n", start_lbl);
            fprintf(g->output, ".L%d:\n", end_lbl);
            break;
        }

        case AST_BLOCK: {
            for (int i = 0; i < stmt->data.block.statement_count; i++)
                generate_statement(g, stmt->data.block.statements[i]);
            break;
        }

        default:
            break;
    }
}

/* ─────────────────────────────────────────
   FUNCTION CODE GENERATOR
   Handles both 'main' (entry point) and user-defined functions.

   Stack frame layout:
     [rbp]       = saved rbp
     [rbp - 8]   = param[0]   (if any)
     [rbp - 16]  = param[1]   (if any)
     ...
     [rbp - N]   = local var  (var x = ...)
───────────────────────────────────────── */

static void generate_function(CodeGenerator* g, ASTNode* func) {
    const char* name     = func->data.function.name;
    int         nparams  = func->data.function.param_count;

    /* reset per-function state */
    free_var_list();
    g->current_function = name;

    /* label: _start for main, function name for everything else */
    if (strcmp(name, "main") == 0) {
        fprintf(g->output, "_start:\n");
    } else {
        fprintf(g->output, "%s:\n", name);
    }

    /* prologue */
    fprintf(g->output, "    push rbp\n");
    fprintf(g->output, "    mov  rbp, rsp\n");

    /*
     * Parameters arrive in rdi, rsi, rdx, rcx, r8, r9.
     * Spill them onto the stack immediately so the rest of codegen
     * can treat params exactly like local variables ([rbp - N]).
     */
    for (int i = 0; i < nparams && i < MAX_REG_ARGS; i++) {
        current_offset += 8;
        add_variable(func->data.function.params[i], current_offset, 0);
        fprintf(g->output, "    sub  rsp, 8\n");
        fprintf(g->output, "    mov  [rbp - %d], %s\n",
                current_offset, ARG_REGS[i]);
    }

    /* body */
    generate_statement(g, func->data.function.body);

    /* epilogue label — every return statement jumps here */
    fprintf(g->output, ".L_ret_%s:\n", name);
    fprintf(g->output, "    mov  rsp, rbp\n");
    fprintf(g->output, "    pop  rbp\n");

    if (strcmp(name, "main") == 0) {
        /* exit(0) */
        fprintf(g->output, "    mov  rax, 60\n");
        fprintf(g->output, "    mov  rdi, 0\n");
        fprintf(g->output, "    syscall\n\n");
    } else {
        /* normal return — value already in rax */
        fprintf(g->output, "    ret\n\n");
    }
}

/* ─────────────────────────────────────────
   PUBLIC API
───────────────────────────────────────── */

CodeGenerator* create_code_generator(const char* filename) {
    CodeGenerator* g = safe_malloc(sizeof(CodeGenerator));
    g->output           = fopen(filename, "w");
    if (!g->output) {
        fprintf(stderr, "CodeGen Error: Cannot open '%s'\n", filename);
        exit(1);
    }
    g->label_counter    = 0;
    g->stack_offset     = 0;
    g->current_function = "";
    var_list            = NULL;
    current_offset      = 0;
    str_count           = 0;
    data_section[0]     = '\0';
    return g;
}

void free_code_generator(CodeGenerator* g) {
    if (!g) return;
    if (g->output) fclose(g->output);
    free_var_list();
    free(g);
}

void generate_code(CodeGenerator* g, ASTNode* program) {

    generate_prologue(g);   /* section .text + print_int + print_str */

    if (!program || program->type != AST_PROGRAM) return;

    /*
     * Emit non-main functions first so they are defined before _start
     * calls them. (NASM doesn't require forward declarations, but it's
     * cleaner to have callee before caller.)
     */
    for (int pass = 0; pass < 2; pass++) {
        for (int i = 0; i < program->data.program.function_count; i++) {
            ASTNode* func = program->data.program.functions[i];
            if (!func || func->type != AST_FUNCTION) continue;

            int is_main = strcmp(func->data.function.name, "main") == 0;
            if (pass == 0 && is_main)  continue;  /* skip main on pass 0 */
            if (pass == 1 && !is_main) continue;  /* skip non-main on pass 1 */

            generate_function(g, func);
        }
    }

    /* String literal pool — appended at the end, NASM merges .data sections */
    if (str_count > 0) {
        fprintf(g->output, "\nsection .data\n");
        fprintf(g->output, "%s", data_section);
    }

    printf("Code generation completed: output.asm\n");
}