#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ─────────────────────────────────────────
   VARIABLE TABLE
───────────────────────────────────────── */
typedef struct VarOffset {
    char* name;
    int   offset;
    int   is_string;
    int   is_list;
    int   is_bool;
    struct VarOffset* next;
} VarOffset;

static VarOffset* var_list      = NULL;
static int        current_offset = 0;
static char       data_section[10000] = "";
static int        str_count     = 0;

static const char* ARG_REGS[] = { "rdi", "rsi", "rdx", "rcx", "r8", "r9" };
#define MAX_REG_ARGS 6

static VarOffset* find_var(const char* name) {
    for (VarOffset* v = var_list; v; v = v->next)
        if (strcmp(v->name, name) == 0) return v;
    return NULL;
}
static int get_variable_offset   (const char* n){ VarOffset* v=find_var(n); return v?v->offset:-1; }
static int get_variable_is_string(const char* n){ VarOffset* v=find_var(n); return v?v->is_string:0; }
static int get_variable_is_list  (const char* n){ VarOffset* v=find_var(n); return v?v->is_list:0; }
static int get_variable_is_bool  (const char* n){ VarOffset* v=find_var(n); return v?v->is_bool:0; }

static void add_variable(const char* name, int offset,
                         int is_string, int is_list, int is_bool) {
    VarOffset* v = malloc(sizeof(VarOffset));
    v->name=strdup(name); v->offset=offset;
    v->is_string=is_string; v->is_list=is_list; v->is_bool=is_bool;
    v->next=var_list; var_list=v;
}
static void free_var_list(void) {
    VarOffset* c=var_list;
    while(c){VarOffset* n=c->next;free(c->name);free(c);c=n;}
    var_list=NULL; current_offset=0;
}

/* ─────────────────────────────────────────
   LOOP LABEL STACK
   Used so that  break  and  skip  inside a
   nested loop know which labels to jump to.

   Each loop pushes its start/end labels onto
   the stack before generating its body, then
   pops them after.

     break  →  jmp  .L<end>    (exit loop)
     skip   →  jmp  .L<continue_target>

   For a  while  loop:
     continue_target = start  (re-evaluate condition)

   For a  for  loop:
     continue_target = update label  (run i=i+1 first)
───────────────────────────────────────── */
#define MAX_LOOP_DEPTH 64

typedef struct {
    int break_label;     /* label to jump to on break  */
    int continue_label;  /* label to jump to on skip   */
} LoopFrame;

static LoopFrame loop_stack[MAX_LOOP_DEPTH];
static int       loop_depth = 0;

static void push_loop(int break_lbl, int continue_lbl) {
    if (loop_depth >= MAX_LOOP_DEPTH) {
        fprintf(stderr, "CodeGen: loop nesting too deep\n"); exit(1);
    }
    loop_stack[loop_depth].break_label    = break_lbl;
    loop_stack[loop_depth].continue_label = continue_lbl;
    loop_depth++;
}

static void pop_loop(void) {
    if (loop_depth > 0) loop_depth--;
}

static int current_break_label(void) {
    if (loop_depth == 0) { fprintf(stderr,"CodeGen: break outside loop\n"); exit(1); }
    return loop_stack[loop_depth-1].break_label;
}

static int current_continue_label(void) {
    if (loop_depth == 0) { fprintf(stderr,"CodeGen: skip outside loop\n"); exit(1); }
    return loop_stack[loop_depth-1].continue_label;
}

/* ─────────────────────────────────────────
   HELPERS
───────────────────────────────────────── */
static int new_label(CodeGenerator* g) { return g->label_counter++; }

static int register_string(const char* value) {
    int id = str_count++;
    char buf[1024];
    snprintf(buf, sizeof(buf), "str%d db \"%s\", 0\n", id, value);
    strncat(data_section, buf, sizeof(data_section)-strlen(data_section)-1);
    return id;
}

static int bool_str_yes_id = -1;
static int bool_str_no_id  = -1;

/* ─────────────────────────────────────────
   PROLOGUE
───────────────────────────────────────── */
static void generate_prologue(CodeGenerator* g) {
    fprintf(g->output, "; Generated by Simple Compiler\n\n");
    fprintf(g->output, "section .text\nglobal _start\n\n");

    /* print_int */
    fprintf(g->output,
        "print_int:\n"
        "    push rbp\n    mov  rbp, rsp\n    sub  rsp, 64\n"
        "    mov  rax, rdi\n    mov  r8,  0\n    mov  rbx, 10\n"
        ".pi_convert:\n"
        "    xor  rdx, rdx\n    div  rbx\n    add  dl, '0'\n"
        "    dec  rsp\n    mov  [rsp], dl\n    inc  r8\n"
        "    test rax, rax\n    jnz  .pi_convert\n"
        ".pi_print:\n"
        "    test r8, r8\n    jz   .pi_newline\n"
        "    mov  rax, 1\n    mov  rdi, 1\n    mov  rsi, rsp\n    mov  rdx, 1\n"
        "    syscall\n    inc  rsp\n    dec  r8\n    jmp  .pi_print\n"
        ".pi_newline:\n"
        "    mov  byte [rbp-1], 10\n"
        "    mov  rax, 1\n    mov  rdi, 1\n    lea  rsi, [rbp-1]\n    mov  rdx, 1\n"
        "    syscall\n    mov  rsp, rbp\n    pop  rbp\n    ret\n\n"
    );

    /* print_str — save rdi into rsi BEFORE overwriting rdi with fd=1 */
    fprintf(g->output,
        "print_str:\n"
        "    push rbp\n    mov  rbp, rsp\n    sub  rsp, 16\n"
        "    mov  r8, 0\n"
        ".ps_len:\n"
        "    mov  al, [rdi + r8]\n    test al, al\n    jz   .ps_write\n"
        "    inc  r8\n    jmp  .ps_len\n"
        ".ps_write:\n"
        "    test r8, r8\n    jz   .ps_newline\n"
        "    mov  rax, 1\n"
        "    mov  rsi, rdi\n"   /* string ptr → rsi FIRST */
        "    mov  rdx, r8\n"
        "    mov  rdi, 1\n"     /* fd = stdout */
        "    syscall\n"
        ".ps_newline:\n"
        "    mov  byte [rbp-1], 10\n"
        "    mov  rax, 1\n    mov  rdi, 1\n    lea  rsi, [rbp-1]\n    mov  rdx, 1\n"
        "    syscall\n    mov  rsp, rbp\n    pop  rbp\n    ret\n\n"
    );

    /* list_alloc */
    fprintf(g->output,
        "list_alloc:\n"
        "    push rbp\n    mov  rbp, rsp\n"
        "    push rbx\n    push r12\n    push r13\n"
        "    mov  r12, rdi\n    mov  r13, rdi\n    imul r13, 2\n"
        "    cmp  r13, 8\n    jge  .la_cap_ok\n    mov  r13, 8\n"
        ".la_cap_ok:\n"
        "    xor  rdi, rdi\n    mov  rax, 12\n    syscall\n"
        "    mov  rbx, rax\n"
        "    mov  rdi, rax\n    mov  rcx, r13\n    imul rcx, 8\n"
        "    add  rdi, rcx\n    add  rdi, 16\n    mov  rax, 12\n    syscall\n"
        "    mov  [rbx],     r12\n    mov  [rbx + 8], r13\n    mov  rax, rbx\n"
        "    pop  r13\n    pop  r12\n    pop  rbx\n"
        "    mov  rsp, rbp\n    pop  rbp\n    ret\n\n"
    );

    /* list_push */
    fprintf(g->output,
        "list_push:\n"
        "    push rbp\n    mov  rbp, rsp\n"
        "    push rbx\n    push r12\n    push r13\n    push r14\n"
        "    mov  rbx, rdi\n    mov  r12, rsi\n"
        "    mov  r13, [rbx]\n    mov  r14, [rbx + 8]\n"
        "    cmp  r13, r14\n    jl   .lp_has_space\n"
        "    imul r14, 2\n    mov  [rbx + 8], r14\n"
        "    xor  rdi, rdi\n    mov  rax, 12\n    syscall\n"
        "    mov  rdi, rax\n    mov  rcx, r14\n    imul rcx, 8\n"
        "    add  rdi, rcx\n    add  rdi, 16\n    mov  rax, 12\n    syscall\n"
        ".lp_has_space:\n"
        "    mov  rcx, r13\n    imul rcx, 8\n    add  rcx, 16\n"
        "    mov  [rbx + rcx], r12\n    inc  r13\n    mov  [rbx], r13\n"
        "    pop  r14\n    pop  r13\n    pop  r12\n    pop  rbx\n"
        "    mov  rsp, rbp\n    pop  rbp\n    ret\n\n"
    );

    /* list_len */
    fprintf(g->output, "list_len:\n    mov  rax, [rdi]\n    ret\n\n");
}

static void generate_expression(CodeGenerator* g, ASTNode* expr);

/* ── emit_output ── */
static void emit_output(CodeGenerator* g, ASTNode* arg) {
    if (!arg) return;

    if (arg->type == AST_STRING) {
        int id = register_string(arg->data.string_value);
        fprintf(g->output, "    lea  rdi, [rel str%d]\n    call print_str\n", id);
        return;
    }
    if (arg->type == AST_BOOL) {
        if (bool_str_yes_id < 0) bool_str_yes_id = register_string("yes");
        if (bool_str_no_id  < 0) bool_str_no_id  = register_string("no");
        int id = arg->data.bool_value ? bool_str_yes_id : bool_str_no_id;
        fprintf(g->output, "    lea  rdi, [rel str%d]\n    call print_str\n", id);
        return;
    }
    if (arg->type == AST_IDENTIFIER) {
        int off     = get_variable_offset(arg->data.identifier);
        int is_str  = get_variable_is_string(arg->data.identifier);
        int is_bool = get_variable_is_bool(arg->data.identifier);
        if (off < 0) { fprintf(stderr,"Undefined '%s'\n",arg->data.identifier); exit(1); }

        if (is_str) {
            fprintf(g->output, "    mov  rdi, [rbp - %d]\n    call print_str\n", off);
            return;
        }
        if (is_bool) {
            if (bool_str_yes_id < 0) bool_str_yes_id = register_string("yes");
            if (bool_str_no_id  < 0) bool_str_no_id  = register_string("no");
            int l_yes = new_label(g), l_end = new_label(g);
            fprintf(g->output, "    mov  rax, [rbp - %d]\n", off);
            fprintf(g->output, "    cmp  rax, 0\n    jne  .L%d\n", l_yes);
            fprintf(g->output, "    lea  rdi, [rel str%d]\n    call print_str\n", bool_str_no_id);
            fprintf(g->output, "    jmp  .L%d\n", l_end);
            fprintf(g->output, ".L%d:\n", l_yes);
            fprintf(g->output, "    lea  rdi, [rel str%d]\n    call print_str\n", bool_str_yes_id);
            fprintf(g->output, ".L%d:\n", l_end);
            return;
        }
        fprintf(g->output, "    mov  rdi, [rbp - %d]\n    call print_int\n", off);
        return;
    }
    /* any other expression → evaluate → print_int */
    generate_expression(g, arg);
    fprintf(g->output, "    mov  rdi, rax\n    call print_int\n");
}

/* ── expression generator ── */
static void generate_expression(CodeGenerator* g, ASTNode* expr) {
    if (!expr) return;
    switch (expr->type) {

        case AST_INTEGER:
            fprintf(g->output, "    mov  rax, %d\n", expr->data.int_value); break;

        case AST_BOOL:
            fprintf(g->output, "    mov  rax, %d\n", expr->data.bool_value); break;

        case AST_CHAR:
            fprintf(g->output, "    mov  rax, %d\n", (int)expr->data.char_value); break;

        case AST_STRING: {
            int id = register_string(expr->data.string_value);
            fprintf(g->output, "    lea  rax, [rel str%d]\n", id); break;
        }

        case AST_IDENTIFIER: {
            int off = get_variable_offset(expr->data.identifier);
            if (off < 0) { fprintf(stderr,"Undefined '%s'\n",expr->data.identifier); exit(1); }
            fprintf(g->output, "    mov  rax, [rbp - %d]\n", off); break;
        }

        case AST_BINARY_OP: {
            generate_expression(g, expr->data.binary.left);
            fprintf(g->output, "    push rax\n");
            generate_expression(g, expr->data.binary.right);
            fprintf(g->output, "    mov  rbx, rax\n    pop  rax\n");
            switch (expr->data.binary.op) {
                case TOKEN_PLUS:          fprintf(g->output,"    add  rax, rbx\n"); break;
                case TOKEN_MINUS:         fprintf(g->output,"    sub  rax, rbx\n"); break;
                case TOKEN_STAR:          fprintf(g->output,"    imul rax, rbx\n"); break;
                case TOKEN_SLASH:         fprintf(g->output,"    cqo\n    idiv rbx\n"); break;
                case TOKEN_GREATER:       fprintf(g->output,"    cmp rax,rbx\n    setg  al\n    movzx rax,al\n"); break;
                case TOKEN_LESS:          fprintf(g->output,"    cmp rax,rbx\n    setl  al\n    movzx rax,al\n"); break;
                case TOKEN_GREATER_EQUAL: fprintf(g->output,"    cmp rax,rbx\n    setge al\n    movzx rax,al\n"); break;
                case TOKEN_LESS_EQUAL:    fprintf(g->output,"    cmp rax,rbx\n    setle al\n    movzx rax,al\n"); break;
                case TOKEN_EQUAL:         fprintf(g->output,"    cmp rax,rbx\n    sete  al\n    movzx rax,al\n"); break;
                case TOKEN_NOT_EQUAL:     fprintf(g->output,"    cmp rax,rbx\n    setne al\n    movzx rax,al\n"); break;
                case TOKEN_AND:
                    fprintf(g->output,"    test rax,rax\n    setnz al\n");
                    fprintf(g->output,"    test rbx,rbx\n    setnz bl\n");
                    fprintf(g->output,"    and  al,bl\n    movzx rax,al\n"); break;
                case TOKEN_OR:
                    fprintf(g->output,"    test rax,rax\n    setnz al\n");
                    fprintf(g->output,"    test rbx,rbx\n    setnz bl\n");
                    fprintf(g->output,"    or   al,bl\n    movzx rax,al\n"); break;
                default: fprintf(stderr,"Unsupported operator\n"); exit(1);
            }
            break;
        }

        case AST_UNARY_OP:
            generate_expression(g, expr->data.unary.operand);
            if (expr->data.unary.op == TOKEN_NOT)
                fprintf(g->output,"    test rax,rax\n    setz al\n    movzx rax,al\n");
            else if (expr->data.unary.op == TOKEN_MINUS)
                fprintf(g->output,"    neg  rax\n");
            break;

        case AST_INDEX:
            generate_expression(g, expr->data.index_expr.object);
            fprintf(g->output,"    mov  r10, rax\n");
            generate_expression(g, expr->data.index_expr.index);
            fprintf(g->output,"    mov  rbx, rax\n    imul rbx, 8\n    add  rbx, 16\n");
            fprintf(g->output,"    add  rbx, r10\n    mov  rax, [rbx]\n"); break;

        case AST_FUNCTION_CALL: {
            const char* fname = expr->data.func_call.name;
            int nargs = expr->data.func_call.arg_count;
            if (strcmp(fname,"output")==0 && nargs>0)
                { emit_output(g,expr->data.func_call.arguments[0]); break; }
            if (strcmp(fname,"len")==0 && nargs==1) {
                generate_expression(g,expr->data.func_call.arguments[0]);
                fprintf(g->output,"    mov  rdi, rax\n    call list_len\n"); break;
            }
            if (strcmp(fname,"push")==0 && nargs==2) {
                generate_expression(g,expr->data.func_call.arguments[0]);
                fprintf(g->output,"    push rax\n");
                generate_expression(g,expr->data.func_call.arguments[1]);
                fprintf(g->output,"    mov  rsi, rax\n    pop  rdi\n    call list_push\n"); break;
            }
            for (int i=0;i<nargs&&i<MAX_REG_ARGS;i++){
                generate_expression(g,expr->data.func_call.arguments[i]);
                fprintf(g->output,"    push rax\n");
            }
            for (int i=(nargs<MAX_REG_ARGS?nargs:MAX_REG_ARGS)-1;i>=0;i--)
                fprintf(g->output,"    pop  %s\n",ARG_REGS[i]);
            fprintf(g->output,"    call %s\n",fname); break;
        }

        default: break;
    }
}

/* ─────────────────────────────────────────
   STATEMENT GENERATOR
───────────────────────────────────────── */
static void generate_statement(CodeGenerator* g, ASTNode* stmt) {
    if (!stmt) return;
    switch (stmt->type) {

        case AST_VAR_DECL: {
            current_offset += 8;
            ASTNode* init = stmt->data.var_decl.initializer;
            int is_list   = (init && init->type==AST_LIST_LITERAL)?1:0;
            int is_string = (init && init->type==AST_STRING)?1:0;
            int is_bool   = 0;
            if (init) {
                if (init->type == AST_BOOL) is_bool=1;
                else if (init->type==AST_UNARY_OP && init->data.unary.op==TOKEN_NOT) is_bool=1;
                else if (init->type==AST_BINARY_OP) {
                    TokenType op=init->data.binary.op;
                    if (op==TOKEN_EQUAL||op==TOKEN_NOT_EQUAL||
                        op==TOKEN_LESS||op==TOKEN_LESS_EQUAL||
                        op==TOKEN_GREATER||op==TOKEN_GREATER_EQUAL||
                        op==TOKEN_AND||op==TOKEN_OR) is_bool=1;
                }
                if (init->type==AST_IDENTIFIER && get_variable_is_bool(init->data.identifier))
                    is_bool=1;
                if (init->type==AST_FUNCTION_CALL &&
                    strncmp(init->data.func_call.name,"is",2)==0) is_bool=1;
            }
            add_variable(stmt->data.var_decl.name,current_offset,is_string,is_list,is_bool);
            fprintf(g->output,"    sub  rsp, 8\n");
            if (is_list) {
                int count=init->data.list_literal.count;
                fprintf(g->output,"    mov  rdi, %d\n    call list_alloc\n",count);
                fprintf(g->output,"    mov  [rbp - %d], rax\n",current_offset);
                for (int i=0;i<count;i++){
                    fprintf(g->output,"    mov  r10, [rbp - %d]\n",current_offset);
                    generate_expression(g,init->data.list_literal.elements[i]);
                    fprintf(g->output,"    mov  [r10 + %d], rax\n",16+i*8);
                }
            } else if (is_string) {
                int id=register_string(init->data.string_value);
                fprintf(g->output,"    lea  rax, [rel str%d]\n    mov  [rbp - %d], rax\n",id,current_offset);
            } else if (init) {
                generate_expression(g,init);
                fprintf(g->output,"    mov  [rbp - %d], rax\n",current_offset);
            }
            break;
        }

        case AST_LIST_ASSIGN: {
            int off=get_variable_offset(stmt->data.list_assign.name);
            if (off<0){fprintf(stderr,"Undefined list '%s'\n",stmt->data.list_assign.name);exit(1);}
            fprintf(g->output,"    mov  r10, [rbp - %d]\n",off);
            generate_expression(g,stmt->data.list_assign.index);
            fprintf(g->output,"    mov  r11, rax\n");
            generate_expression(g,stmt->data.list_assign.value);
            fprintf(g->output,"    imul r11, 8\n    add  r11, 16\n    add  r11, r10\n");
            fprintf(g->output,"    mov  [r11], rax\n"); break;
        }

        case AST_FUNCTION_CALL: {
            if (strcmp(stmt->data.func_call.name,"output")==0 &&
                stmt->data.func_call.arg_count>0)
                emit_output(g,stmt->data.func_call.arguments[0]);
            else {
                ASTNode tmp; tmp.type=AST_FUNCTION_CALL;
                tmp.data.func_call=stmt->data.func_call;
                generate_expression(g,&tmp);
            }
            break;
        }

        case AST_ASSIGNMENT: {
            int off=get_variable_offset(stmt->data.assignment.name);
            if (off<0){fprintf(stderr,"Undefined var '%s'\n",stmt->data.assignment.name);exit(1);}
            generate_expression(g,stmt->data.assignment.value);
            fprintf(g->output,"    mov  [rbp - %d], rax\n",off); break;
        }

        case AST_RETURN:
            if (stmt->data.return_value)
                generate_expression(g,stmt->data.return_value);
            fprintf(g->output,"    jmp  .L_ret_%s\n",g->current_function); break;

        case AST_IF: {
            int else_l=new_label(g), end_l=new_label(g);
            generate_expression(g,stmt->data.if_stmt.condition);
            fprintf(g->output,"    cmp  rax, 0\n    je   .L%d\n",else_l);
            generate_statement(g,stmt->data.if_stmt.then_branch);
            fprintf(g->output,"    jmp  .L%d\n.L%d:\n",end_l,else_l);
            if (stmt->data.if_stmt.else_branch)
                generate_statement(g,stmt->data.if_stmt.else_branch);
            fprintf(g->output,".L%d:\n",end_l); break;
        }

        /*
         * WHILE loop with break/skip support:
         *
         *   .Lstart:          ← continue_label (skip jumps here)
         *     evaluate condition
         *     cmp rax, 0
         *     je  .Lend       ← break_label    (break  jumps here)
         *     body
         *     jmp .Lstart
         *   .Lend:
         */
        case AST_WHILE: {
            int start = new_label(g);
            int end   = new_label(g);
            /* skip → re-evaluate condition (jump to start) */
            push_loop(end, start);
            fprintf(g->output, ".L%d:\n", start);
            generate_expression(g, stmt->data.while_stmt.condition);
            fprintf(g->output, "    cmp  rax, 0\n    je   .L%d\n", end);
            generate_statement(g, stmt->data.while_stmt.body);
            fprintf(g->output, "    jmp  .L%d\n", start);
            fprintf(g->output, ".L%d:\n", end);
            pop_loop();
            break;
        }

        /*
         * FOR loop with break/skip support:
         *
         *   init
         *   .Lstart:
         *     evaluate condition
         *     cmp rax, 0
         *     je  .Lend         ← break jumps here
         *     body
         *   .Lupdate:           ← skip  jumps here (run update first)
         *     update
         *     jmp .Lstart
         *   .Lend:
         *
         * The separate .Lupdate label ensures that  skip  still
         * runs  i = i + 1  before re-checking the condition,
         * which is the correct behaviour (same as C's continue).
         */
        case AST_FOR: {
            int start  = new_label(g);
            int update = new_label(g);
            int end    = new_label(g);
            /* skip → run update then loop (jump to .Lupdate) */
            push_loop(end, update);

            if (stmt->data.for_stmt.init)
                generate_statement(g, stmt->data.for_stmt.init);

            fprintf(g->output, ".L%d:\n", start);
            if (stmt->data.for_stmt.condition) {
                generate_expression(g, stmt->data.for_stmt.condition);
                fprintf(g->output, "    cmp  rax, 0\n    je   .L%d\n", end);
            }
            generate_statement(g, stmt->data.for_stmt.body);

            fprintf(g->output, ".L%d:\n", update);
            if (stmt->data.for_stmt.update)
                generate_statement(g, stmt->data.for_stmt.update);
            fprintf(g->output, "    jmp  .L%d\n", start);
            fprintf(g->output, ".L%d:\n", end);
            pop_loop();
            break;
        }

        /*
         * break — jump to the end label of the innermost loop
         */
        case AST_BREAK:
            fprintf(g->output, "    jmp  .L%d\n", current_break_label());
            break;

        /*
         * skip — jump to the continue label of the innermost loop
         *   while → jumps to .Lstart  (re-checks condition)
         *   for   → jumps to .Lupdate (runs update, then re-checks)
         */
        case AST_SKIP:
            fprintf(g->output, "    jmp  .L%d\n", current_continue_label());
            break;

        case AST_BLOCK:
            for (int i=0;i<stmt->data.block.statement_count;i++)
                generate_statement(g,stmt->data.block.statements[i]);
            break;

        default: break;
    }
}

/* ── function generator ── */
static void generate_function(CodeGenerator* g, ASTNode* func) {
    const char* name    = func->data.function.name;
    int         nparams = func->data.function.param_count;

    free_var_list();
    g->current_function = name;
    bool_str_yes_id = -1;
    bool_str_no_id  = -1;
    loop_depth = 0;   /* reset loop stack per function */

    if (strcmp(name,"main")==0) fprintf(g->output,"_start:\n");
    else                        fprintf(g->output,"%s:\n",name);

    fprintf(g->output,"    push rbp\n    mov  rbp, rsp\n");

    for (int i=0;i<nparams&&i<MAX_REG_ARGS;i++){
        current_offset+=8;
        add_variable(func->data.function.params[i],current_offset,0,0,0);
        fprintf(g->output,"    sub  rsp, 8\n");
        fprintf(g->output,"    mov  [rbp - %d], %s\n",current_offset,ARG_REGS[i]);
    }

    generate_statement(g,func->data.function.body);

    fprintf(g->output,".L_ret_%s:\n",name);
    fprintf(g->output,"    mov  rsp, rbp\n    pop  rbp\n");

    if (strcmp(name,"main")==0)
        fprintf(g->output,"    mov  rax, 60\n    mov  rdi, 0\n    syscall\n\n");
    else
        fprintf(g->output,"    ret\n\n");
}

/* ── public API ── */
CodeGenerator* create_code_generator(const char* filename) {
    CodeGenerator* g = safe_malloc(sizeof(CodeGenerator));
    g->output = fopen(filename,"w");
    if (!g->output){fprintf(stderr,"Cannot open '%s'\n",filename);exit(1);}
    g->label_counter=0; g->stack_offset=0; g->current_function="";
    var_list=NULL; current_offset=0; str_count=0; data_section[0]='\0';
    bool_str_yes_id=-1; bool_str_no_id=-1; loop_depth=0;
    return g;
}

void free_code_generator(CodeGenerator* g) {
    if (!g) return;
    if (g->output) fclose(g->output);
    free_var_list(); free(g);
}

void generate_code(CodeGenerator* g, ASTNode* program) {
    generate_prologue(g);
    if (!program || program->type!=AST_PROGRAM) return;
    for (int pass=0;pass<2;pass++) {
        for (int i=0;i<program->data.program.function_count;i++){
            ASTNode* func=program->data.program.functions[i];
            if (!func||func->type!=AST_FUNCTION) continue;
            int is_main=strcmp(func->data.function.name,"main")==0;
            if (pass==0&&is_main) continue;
            if (pass==1&&!is_main) continue;
            generate_function(g,func);
        }
    }
    if (str_count>0){
        fprintf(g->output,"\nsection .data\n");
        fprintf(g->output,"%s",data_section);
    }
    printf("Code generation completed: output.asm\n");
}